In [2]:
import numpy as np

In [3]:
dat = np.loadtxt("pose_table.csv", delimiter=",")
dat

array([[ 295.,   93.,  298.,  100.,  291.,  102.,  286.,  113.,  288.,
         120.,  305.,   98.,  313.,  110.,  307.,  124.,  293.,  124.,
         293.,  139.,  294.,  158.,  304.,  123.,  304.,  140.,  304.,
         157.,  294.,   90.,  298.,   89.,  293.,   93.,  302.,   90.],
       [ 291.,  108.,  292.,  120.,  282.,  123.,  281.,  139.,  280.,
         152.,  303.,  119.,  307.,  138.,  312.,  152.,  289.,  151.,
         291.,  172.,  293.,  191.,  302.,  150.,  304.,  171.,  305.,
         190.,  286.,  107.,  292.,  107.,  283.,  108.,  294.,  107.],
       [ 252.,  160.,  261.,  169.,  243.,  170.,  239.,  193.,  247.,
         204.,  276.,  168.,  283.,  192.,  271.,  204.,  259.,  210.,
         261.,  229.,  266.,  246.,  274.,  205.,  282.,  225.,  283.,
         244.,  249.,  159.,  253.,  157.,   -1.,   -1.,  262.,  149.],
       [ 233.,  245.,  246.,  245.,  224.,  246.,  219.,  279.,  223.,
         300.,  269.,  244.,  281.,  274.,  264.,  292.,  242.,  290.,
         229.,  310.,  252.,  325.,  267.,  288.,  274.,  303.,  282.,
         320.,  230.,  243.,  239.,  242.,   -1.,   -1.,  249.,  232.],
       [ 271.,  311.,  260.,  318.,  244.,  332.,  261.,  363.,  292.,
         367.,  272.,  301.,  291.,  318.,  304.,  330.,  270.,  359.,
         284.,  370.,  302.,  367.,  286.,  343.,  310.,  342.,  315.,
         353.,  263.,  310.,  271.,  307.,  252.,  312.,   -1.,   -1.],
       [  -1.,   -1.,  374.,  295.,  393.,  308.,  398.,  330.,   -1.,
          -1.,  349.,  280.,  335.,  312.,   -1.,   -1.,  372.,  345.,
          -1.,   -1.,   -1.,   -1.,  349.,  338.,   -1.,   -1.,   -1.,
          -1.,   -1.,   -1.,   -1.,   -1.,  399.,  278.,  377.,  264.],
       [  -1.,   -1.,  407.,  216.,  425.,  217.,  430.,  238.,   -1.,
          -1.,  387.,  216.,  370.,  237.,  364.,  247.,  407.,  266.,
         383.,  280.,  377.,  300.,  387.,  262.,  378.,  285.,  377.,
         307.,   -1.,   -1.,   -1.,   -1.,  421.,  195.,  401.,  191.],
       [  -1.,   -1.,  391.,  159.,  406.,  159.,  412.,  178.,   -1.,
          -1.,  378.,  158.,  364.,  171.,  367.,  159.,  393.,  199.,
         387.,  219.,  388.,  226.,  378.,  195.,  375.,  218.,  376.,
         244.,   -1.,   -1.,   -1.,   -1.,  399.,  138.,  386.,  137.],
       [  -1.,   -1.,  372.,  120.,  382.,  121.,  388.,  139.,  382.,
         148.,  359.,  120.,  354.,  138.,  351.,  149.,  377.,  151.,
         376.,  171.,  375.,  190.,  365.,  151.,  364.,  170.,  365.,
         191.,   -1.,   -1.,   -1.,   -1.,  377.,  107.,  366.,  107.],
       [  -1.,   -1.,  349.,  104.,  357.,  104.,  363.,  117.,  359.,
         127.,  343.,  105.,  338.,  117.,  337.,  128.,  356.,  128.,
         356.,  149.,  356.,  168.,  346.,  129.,  345.,  149.,  347.,
         167.,   -1.,   -1.,   -1.,   -1.,  353.,   93.,  345.,   93.],
       [ 324.,   86.,  333.,   94.,  335.,   94.,  337.,  106.,  335.,
         117.,  328.,   94.,  328.,  106.,  326.,  118.,  336.,  116.,
         335.,  131.,  336.,  148.,  333.,  116.,  329.,  130.,  328.,
         147.,  325.,   85.,  325.,   85.,   -1.,   -1.,  326.,   85.],
       [ 298.,   87.,  303.,   95.,  296.,   96.,  293.,  106.,  290.,
         111.,  309.,   95.,  315.,  106.,  317.,  116.,  303.,  117.,
         303.,  135.,  305.,  149.,  312.,  117.,  313.,  133.,  316.,
         147.,  296.,   86.,  301.,   86.,  296.,   87.,  303.,   86.],
       [ 303.,   95.,  302.,  103.,  293.,  104.,  289.,  116.,  293.,
         126.,  310.,  103.,  315.,  114.,  315.,  127.,  296.,  127.,
         301.,  146.,  303.,  161.,  306.,  127.,  305.,  146.,  304.,
         161.,  301.,   93.,  304.,   93.,  296.,   95.,  305.,   94.],
       [ 337.,  107.,  335.,  118.,  324.,  118.,  316.,  133.,  316.,
         147.,  346.,  118.,  349.,  133.,  351.,  145.,  328.,  150.,
         332.,  171.,  329.,  189.,  342.,  149.,  343.,  171.,  338.,
         189.,  335.,  106.,  340.,  106.,  331.,  106.,  342.,  107.],
       [ 376.,  146.,  368.,  155.,  356.,  153.,  345.,  171.,  346.,
         189.,  381.,  156.,  384.,  172.,  386.,  188.,  358.,  191.,
         355.,  214.,  356.,  230.,  375.,  192.,  375.,  216.,  369.,
         243.,  373.,  140.,  378.,  141.,  366.,  139.,  381.,  139.],
       [ 403.,  210.,  398.,  212.,  379.,  212.,  366.,  232.,  358.,
         253.,  416.,  213.,  418.,  235.,  411.,  254.,  379.,  251.,
         376.,  268.,  377.,  286.,  399.,  254.,  397.,  277.,  387.,
         308.,  399.,  203.,  408.,  203.,  391.,  197.,  414.,  199.],
       [ 321.,  259.,  338.,  264.,  347.,  258.,  326.,  272.,  308.,
         277.,  334.,  266.,  317.,  269.,  306.,  275.,  359.,  308.,
         317.,  296.,  333.,  330.,  348.,  311.,  324.,  298.,  346.,
         332.,   -1.,   -1.,  320.,  255.,  340.,  248.,  324.,  254.],
       [  -1.,   -1.,  243.,  265.,  264.,  263.,  287.,  279.,  290.,
         260.,  224.,  267.,  222.,  290.,   -1.,   -1.,  271.,  307.,
         292.,  290.,  282.,  332.,  251.,  308.,   -1.,   -1.,   -1.,
          -1.,   -1.,   -1.,   -1.,   -1.,  250.,  237.,  229.,  243.],
       [  -1.,   -1.,  291.,  189.,  304.,  189.,  314.,  213.,  324.,
         201.,  274.,  188.,  274.,  213.,  282.,  225.,  308.,  228.,
         314.,  254.,  303.,  278.,  294.,  232.,  310.,  253.,  304.,
         276.,   -1.,   -1.,   -1.,   -1.,  299.,  167.,  282.,  168.],
       [  -1.,   -1.,  327.,  140.,  343.,  141.,  346.,  163.,  345.,
         172.,  314.,  140.,  312.,  163.,  311.,  181.,  337.,  178.,
         337.,  200.,  334.,  222.,  324.,  179.,  333.,  200.,  333.,
         221.,   -1.,   -1.,   -1.,   -1.,  335.,  126.,  324.,  125.],
       [  -1.,   -1.,  344.,  115.,  354.,  115.,  356.,  129.,  356.,
         140.,  334.,  114.,  328.,  129.,  326.,  144.,  347.,  141.,
         347.,  161.,  346.,  180.,  336.,  141.,  336.,  160.,  336.,
         180.,   -1.,   -1.,   -1.,   -1.,  348.,  103.,  341.,   99.],
       [ 322.,   95.,  332.,  100.,  336.,   98.,  342.,  115.,  339.,
         126.,  325.,  102.,  324.,  115.,  323.,  127.,  336.,  126.,
         335.,  144.,  337.,  160.,  327.,  127.,  327.,  144.,  332.,
         159.,   -1.,   -1.,  322.,   93.,  333.,   93.,  325.,   91.],
       [ 288.,   88.,  295.,   95.,  303.,   94.,  307.,  105.,  305.,
         113.,  292.,   96.,  290.,  108.,  289.,  117.,  304.,  116.,
         303.,  134.,  304.,  149.,  295.,  117.,  293.,  131.,  294.,
         148.,   -1.,   -1.,  288.,   86.,  295.,   85.,  291.,   86.]])

In [4]:
dat2 = np.arange(20).reshape((4,5))
dat2[1][1] = -1
dat2[0][3] = dat2[1][3] = dat2[2][3] = -1
dat2

array([[ 0,  1,  2, -1,  4],
       [ 5, -1,  7, -1,  9],
       [10, 11, 12, -1, 14],
       [15, 16, 17, 18, 19]])

In [5]:
#dat = dat2.copy()

#[i[0] for i in np.where(dat==-1)]

while True:
    nan_index = np.where(dat==-1)
    if np.shape(nan_index) == (2,0):
        break
    loss_index = [i[0] for i in nan_index]
    
    y0 = y1 = loss_index[0]
    x = loss_index[1]
    range_count = 0
    while True:
        range_count += 1
        y0 -= 1
        try:
            before_val = dat[y0,x]
        except IndexError as err:
            print(err)
            dat[y1+1][x] = dat[y][x]
            break
        if before_val > 0:
            break
    
    while True:
        range_count += 1
        y1 += 1
        try:
            after_val = dat[y1,x]
        except IndexError as err:
            print(err)
            dat[y1-1][x] = dat[y][x]
            break
        if after_val > 0:
            break
            
    #t = y1 - y0 - 1
    for i in range(y0+1, y1):
        try:
            print("orig_val", dat[i][x])
            print("y0 i y1 range_count i", y0, i, y1, range_count, i)
            print("y0 i y1 range_count i", dat[y0][x] ,(range_count-i) ,dat[y1][x] ,(i))
            print("result", dat[y0][x] *(range_count-i-1) + dat[y1][x] * (i+1))
        #try:
            dat[i][x] = (dat[y0][x] *(range_count-i) + dat[y1][x] * i) \
                / range_count
        except IndexError as err:
            print(dat)
            np.savetxt("calibrate_test.csv", dat, delimiter=",")
        
    print("-------------------")
    
    #dat[loss_index[0]][loss_index[1]] = 1

print("org", dat2)
print("dat", dat)

('orig_val', -1.0)
('y0 i y1 range_count i', 1, 2, 4, 3, 2)
('y0 i y1 range_count i', 283.0, 1, 252.0, 2)
('result', 756.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 1, 3, 4, 3, 3)
('y0 i y1 range_count i', 283.0, 0, 252.0, 3)
('result', 725.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 1, 2, 4, 3, 2)
('y0 i y1 range_count i', 108.0, 1, 312.0, 2)
('result', 936.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 1, 3, 4, 3, 3)
('y0 i y1 range_count i', 108.0, 0, 312.0, 3)
('result', 1140.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 3, 4, 5, 2, 4)
('y0 i y1 range_count i', 249.0, -2, 377.0, 4)
('result', 1138.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 3, 4, 5, 2, 4)
('y0 i y1 range_count i', 232.0, -2, 264.0, 4)
('result', 624.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 10, 6, 5)
('y0 i y1 range_count i', 271.0, 1, 324.0, 5)
('result', 1944.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 10, 6, 6)
('y0 i y1 range_count i', 271.0, 0, 324.0, 6)
('result', 1997.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 10, 6, 7)
('y0 i y1 range_count i', 271.0, -1, 324.0, 7)
('result', 2050.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 8, 10, 6, 8)
('y0 i y1 range_count i', 271.0, -2, 324.0, 8)
('result', 2103.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 9, 10, 6, 9)
('y0 i y1 range_count i', 271.0, -3, 324.0, 9)
('result', 2156.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 10, 6, 5)
('y0 i y1 range_count i', 311.0, 1, 86.0, 5)
('result', 516.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 10, 6, 6)
('y0 i y1 range_count i', 311.0, 0, 86.0, 6)
('result', 291.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 10, 6, 7)
('y0 i y1 range_count i', 311.0, -1, 86.0, 7)
('result', 66.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 8, 10, 6, 8)
('y0 i y1 range_count i', 311.0, -2, 86.0, 8)
('result', -159.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 9, 10, 6, 9)
('y0 i y1 range_count i', 311.0, -3, 86.0, 9)
('result', -384.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 8, 4, 5)
('y0 i y1 range_count i', 292.0, -1, 382.0, 5)
('result', 1708.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 8, 4, 6)
('y0 i y1 range_count i', 292.0, -2, 382.0, 6)
('result', 1798.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 8, 4, 7)
('y0 i y1 range_count i', 292.0, -3, 382.0, 7)
('result', 1888.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 8, 4, 5)
('y0 i y1 range_count i', 367.0, -1, 148.0, 5)
('result', 154.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 8, 4, 6)
('y0 i y1 range_count i', 367.0, -2, 148.0, 6)
('result', -65.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 8, 4, 7)
('y0 i y1 range_count i', 367.0, -3, 148.0, 7)
('result', -284.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 304.0, -3, 364.0, 5)
('result', 968.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 330.0, -3, 247.0, 5)
('result', 162.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 284.0, -3, 383.0, 5)
('result', 1162.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 370.0, -3, 280.0, 5)
('result', 200.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 302.0, -3, 377.0, 5)
('result', 1054.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 367.0, -3, 300.0, 5)
('result', 332.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 310.0, -3, 378.0, 5)
('result', 1028.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 342.0, -3, 285.0, 5)
('result', 342.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 315.0, -3, 377.0, 5)
('result', 1002.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 6, 2, 5)
('y0 i y1 range_count i', 353.0, -3, 307.0, 5)
('result', 430.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 10, 6, 5)
('y0 i y1 range_count i', 263.0, 1, 325.0, 5)
('result', 1950.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 10, 6, 6)
('y0 i y1 range_count i', 263.0, 0, 325.0, 6)
('result', 2012.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 10, 6, 7)
('y0 i y1 range_count i', 263.0, -1, 325.0, 7)
('result', 2074.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 8, 10, 6, 8)
('y0 i y1 range_count i', 263.0, -2, 325.0, 8)
('result', 2136.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 9, 10, 6, 9)
('y0 i y1 range_count i', 263.0, -3, 325.0, 9)
('result', 2198.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 10, 6, 5)
('y0 i y1 range_count i', 310.0, 1, 85.0, 5)
('result', 510.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 10, 6, 6)
('y0 i y1 range_count i', 310.0, 0, 85.0, 6)
('result', 285.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 10, 6, 7)
('y0 i y1 range_count i', 310.0, -1, 85.0, 7)
('result', 60.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 8, 10, 6, 8)
('y0 i y1 range_count i', 310.0, -2, 85.0, 8)
('result', -165.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 9, 10, 6, 9)
('y0 i y1 range_count i', 310.0, -3, 85.0, 9)
('result', -390.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 10, 6, 5)
('y0 i y1 range_count i', 271.0, 1, 325.0, 5)
('result', 1950.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 10, 6, 6)
('y0 i y1 range_count i', 271.0, 0, 325.0, 6)
('result', 2004.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 10, 6, 7)
('y0 i y1 range_count i', 271.0, -1, 325.0, 7)
('result', 2058.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 8, 10, 6, 8)
('y0 i y1 range_count i', 271.0, -2, 325.0, 8)
('result', 2112.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 9, 10, 6, 9)
('y0 i y1 range_count i', 271.0, -3, 325.0, 9)
('result', 2166.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 5, 10, 6, 5)
('y0 i y1 range_count i', 307.0, 1, 85.0, 5)
('result', 510.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 6, 10, 6, 6)
('y0 i y1 range_count i', 307.0, 0, 85.0, 6)
('result', 288.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 7, 10, 6, 7)
('y0 i y1 range_count i', 307.0, -1, 85.0, 7)
('result', 66.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 8, 10, 6, 8)
('y0 i y1 range_count i', 307.0, -2, 85.0, 8)
('result', -156.0)
('orig_val', -1.0)
('y0 i y1 range_count i', 4, 9, 10, 6, 9)
('y0 i y1 range_count i', 307.0, -3, 85.0, 9)
('result', -378.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 9, 10, 11, 2, 10)
('y0 i y1 range_count i', 353.0, -8, 296.0, 10)
('result', 79.0)
-------------------
('orig_val', -1.0)
('y0 i y1 range_count i', 9, 10, 11, 2, 10)
('y0 i y1 range_count i', 93.0, -8, 87.0, 10)
('result', 120.0)
-------------------
index 23 is out of bounds for axis 0 with size 23

NameError: name 'y' is not defined